on:
    push:
        branches:
            - master
    
name: Deploy to Hostinger

jobs:
    web-deploy:
        name: Deploy to Hostinger
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: running install commands
              run: |
                npm install

            - name: running build commands
              run: |
                npm run build

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                server: ftp.growlimitless.app
                username: u644247801.gllpartners
                password: ${{secrets.FTP_PASSWORD}}
                local-dir: ./out/
                server-dir: ./public_html/partner/
               
                
                
                
                
                
              
              
        